version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app_network
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

  features:
    build:
      context: ./features
    restart: always
    depends_on:
      - rabbitmq
    networks:
      - app_network
    environment:
      - FEATURE_SERVICE_DELAY=10

  model:
    build:
      context: ./model
    restart: always
    depends_on:
      - rabbitmq
      - features
    networks:
      - app_network

  metric:
    build:
      context: ./metric
    restart: always
    depends_on:
      - rabbitmq
      - features
      - model
    volumes:
      - ./logs/:/usr/src/app/logs/
    networks:
      - app_network
    environment:
      - METRIC_LOG_FILE=/usr/src/app/logs/metric_log.csv

  plot:
    build:
      context: ./plot
    restart: always
    depends_on:
      - rabbitmq
      - metric
    volumes:
      - ./logs/:/usr/src/app/logs/
    networks:
      - app_network
    environment:
      - PLOT_UPDATE_INTERVAL=60

networks:
  app_network:
    driver: bridge
